### ISSUE TITLE
0.6.4 memory problems on RPi3 (armv7h)?

### ISSUE THREAD

**Issue by newrokor** [mediathekview/plugin.video.mediathekview#170] opened 2020-06-06 16:31 UTC
Dear all,

I successfully ran and run again 0.6.2 of the plugin on a RPi3, connecting to a local MariaDB, however, I faced memory problems with the latest 0.6.4. It downloaded the Filmliste-akt.xz, decompressed it, took all available physical memory and swap (about 0.5G only), and blocked the RPi - if run as plugin, or run stand alone via mvupdate. Anybody there, who can understand/confirm this?

I know, a RPi is limited in memory and computing power (about 2,5h for a full update, and a few minutes for a diff), but returning to 0.6.2 brings back normal operation. Some more data: It is running on an quite recent Arch Linux ARM using the "kodi-rpi3" packages (18.7), python 3.8.3, python-ijson 3.0.1, python-mysql-connector 8.0.19, and mariadb 10.4.13.

Any hints would be appreciated.

Thanks in advance,
newrokor

**Comment by DokuroKM** [comment] 2020-06-06 17:25
I can confirm that this problem also happens on RPi4 (2GB) with local SQLite database. Had to disable database updates for the moment or I have about 60 seconds until all memory is clogged up.

**Comment by codingPF** [comment] 2020-06-07 10:25
I will check if there is something which can be done to workaround this...
This topic sticks to gather with a couple of thing I would like to change but all this (eg. favorite issue, slowness of MySQL) add up to a solid package of changes which will require some time

**Comment by tanrak** [comment] 2020-06-07 18:23
@codingPF Thanks for investigate.
On RPi3 with SQLite i have the same problem with the new version 0.6.4. For the moment I'm back to last version.

**Comment by newrokor** [comment] 2020-06-08 07:24
@codingPF There is also no need for an immediate work around for me. As mentioned, I will stick with 0.6.2 as long as the problem is there.

The original idea here was to download the DB once and share it locally with different instances of MV. Unfortunately, I could not find the right button up to now in the Java version of MV to make it work with a network-based MariaDB. If I can not realize this to save bandwidth on the server side, using MDB instead of SQLite does not make sense to me. So, if the slowness of MySQL is an issue, I would return to SQLite.

To save more bandwidth, my intention was to run mvupdate (using night hours and times, where nobody is using Kodi here), which worked fine for 0.6.4 - with the exception of the memory leak, but which I could not bring to service up to now for 0.6.2.

If I can assist with tests, feel free to send me a note. Thank you.

**Comment by codingPF** [comment] 2020-06-09 18:51
Tried my best without creating too much changes on the other parts of the code. Please have a look at the attached version.
Thanks
[plugin.video.mediathekview-0.6.5.zip](https://github.com/mediathekview/plugin.video.mediathekview/files/4754216/plugin.video.mediathekview-0.6.5.zip)

**Comment by newrokor** [comment] 2020-06-11 10:56
@codingPF Thanks for the immediate test version. I could test it today, and the preliminary 0.6.5 works running the following CLI commands:

`python ./mvupdate3 mysql -v -p <xxx>`

It is tested under the conditions mentioned above, and needs also about the same time for a full update (2h-2.5h). Some more data for my RPi3 (1GB memory, 0.5G Swap) and the software mentioned above is: mvupdate3 takes about 70% CPU, mysqld about 30%, the load is around 1.7 after higher values at the beginning for a minute or so, iotop mysqld about 0.7MB/s. Just in case this helps for anything.

I could not make it work from within the Kodi GUI, but I am not sure, whether the packages of Arch Linux ARM/AUR are fully consistent in terms of Python v2 vs. v3. If I try to start it manually within the Kodi GUI, I get an indication that an update should be performed, however, it never tries to do so for reasons I did not follow up to now. I am fine with the "mvupdate approach", thank you again.

**Comment by newrokor** [comment] 2020-06-11 13:01
Did I cause the Close? Seems so. Improvement: Read the info of the button, before you press is ;-)

Feel free to reopen it, however, I am fine with the situation as is.

**Comment by codingPF** [comment] 2020-06-11 14:18
No worries 😉

**Comment by MarcusRoeckrath** [comment] 2020-06-13 09:45
Hi,

beginning on May 29 mediathekview 0.6.3/0.6.4 was unable to update the database. On most tries it abort without success or freezes the system (libreelec on wetekplay2).

Yesterday I tried the 0.6.5 release from github and the problem is gone.

Thanks, Marcus

**Comment by codingPF** [comment] 2020-06-14 21:55
Pushed to dev-banch...will close the issue was soon as av. in official Kodi Repo

**Comment by tanrak** [comment] 2020-06-15 19:53
Also v0.6.5 was not really better with LibreElec on my Raspi3 with Sqlite. Permant loop of database update attempt without success and overheating. Than I moved to OSMC for testing the manual update with mvupdate. But that was not necessary. No problem at all even with v0.6.4 on OSMC. I will not really investigate for the problem. I'm now staying with OSMC. It just works.

**Comment by DokuroKM** [comment] 2020-06-15 21:30
That's interesting, as codingPFs version above works on my Raspi4 on LibreElec with Sqlite without any problem.

**Comment by tanrak** [comment] 2020-06-17 09:51
Today I made some tests with `.\mvupdate sqlite -v` and `native=false` (`native=true` works on all Raspis but is no option for me because #125).

**v0.6.5**
Raspi2 (1GB) and Raspi3 (1GB) no success:
```
Starting import of 364025 records from ./Filmliste-akt
Initializing update...
Error  while processing ./Filmliste-akt on update cycle 0
```
Raspi4 (2GB) works.

**v0.6.4**
Raspi2 (1GB) and Raspi3 (1GB) no success:
```
Starting import of 364025 records from ./Filmliste-akt
Initializing update...
Error  while processing ./Filmliste-akt on update cycle 0
```
Raspi4 (2GB) freeze.

**v0.6.2**
Works on all Raspis.

My Kodi is on Raspi3. It would be nice if the database update could work there. Otherwise, I'll just have to use the Raspi4.

**Comment by codingPF** [comment] 2020-11-21 16:26
Kodi Repo Check-in: Version 0.6.6 ist live

**Closed by codingPF** 2020-11-21 16:26 UTC
Labels: done
